// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace webshopApi.Migrations
{
    [DbContext(typeof(webContextDb))]
    [Migration("20190223104155_userInfo")]
    partial class userInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .HasMaxLength(255);

                    b.Property<int>("IdUserInfo");

                    b.Property<string>("Password")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("IdUserInfo");

                    b.ToTable("User");
                });

            modelBuilder.Entity("UsersInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdUser");

                    b.Property<string>("adresa")
                        .HasMaxLength(255);

                    b.Property<string>("brTelefona")
                        .HasMaxLength(255);

                    b.Property<string>("fName")
                        .HasMaxLength(255);

                    b.Property<string>("grad")
                        .HasMaxLength(255);

                    b.Property<string>("lName")
                        .HasMaxLength(255);

                    b.Property<int>("postalCode");

                    b.Property<string>("userName")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("UsersInfo");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("UsersInfo", "UsersInfo")
                        .WithMany()
                        .HasForeignKey("IdUserInfo")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UsersInfo", b =>
                {
                    b.HasOne("User", "user")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
